added check to ensure env vars are set

diff --git a/configure_ec2_node b/configure_ec2_node
--- a/configure_ec2_node
+++ b/configure_ec2_node
@@ -68,6 +68,11 @@ echo "SUCCESS"
 
 # Set the new hostname using the tag from EC2
 new_hostname=`ec2-host-int | grep $(hostname -f) | awk '{print $1}'`
+if [ -z "$new_hostname" ]; then
+    echo "ERROR: Unable to determine Name for node"
+    echo "ERROR: Did you forget to get set the EC2 ENV variables?"
+    exit 1
+fi
 echo -e "\n#####  Setting hostname to $new_hostname"
 sudo sed -i 's|HOSTNAME=.*|HOSTNAME='$new_hostname'|g' /etc/sysconfig/network || exit 1
 cat /etc/sysconfig/network
