move work dir clean up to the init_node tool

diff --git a/init_node b/init_node
--- a/init_node
+++ b/init_node
@@ -41,7 +41,14 @@ fi
 #
 echo -e "\nStarting $SCRIPT_NAME at `date`"
 
-# Setup the work dir
+# Clean up prev work dir
+if [ -d "$work_dir" ]; then
+    echo -e "\n#####  Cleaning up previous work directory $work_dir"
+    rm -rf $work_dir || exit 1
+    echo "SUCCESS"
+fi
+
+# Create new work dir
 if [ ! -d "$work_dir" ]; then
     echo -e "\n#####  Creating work directory $work_dir"
     mkdir -p $work_dir || exit 1
